### ISSUE TITLE
Verify context name existence in 'gdg ctx set -c context_name'

### ISSUE THREAD

**Issue by mvalletta** [netsage-project/grafana-dashboard-manager#30]
Hi @safaci2000 
after I set a wrong context, gdg can't set a correct one.
$ gdg ctx set -c qa
$ gdg ctx list
┌──────┬────┐
│ CONTEXT    │ ACTIVE │
├──────┼────┤
│ production │ false  │
│ qa               │ true   │
└──────┴───┘
$ gdg ctx set -c abc
$ gdg ctx list
time="2021-06-24T10:07:40+02:00" level=error msg="Context is not found.  Please check your config"
$ gdg ctx set -c qa
time="2021-06-24T10:07:47+02:00" level=error msg="Context is not found.  Please check your config"

With the last command I can't set a correct context, so I think it's need to verify the context correctness.
The only way I found to go on it's to edit importer.yml.

**Comment by safaci2000** [comment]
Yeah, I added the set context for convenience sake but probably should do a check before saving the file.
