### ISSUE TITLE
Backup restore without folder filter

### ISSUE THREAD

**Issue by tokheim** [netsage-project/grafana-dashboard-manager#48]
For those that really only are looking for backup/restore functionality it would be really helpful to be able export and import all dashboards irregardless of filters. Managing an up-to-date list of folders just seem like unecessary work.

Sorry if this is already possible, all my attempts with various blank or wildcard or no filters/watched folders have resulted in either General folder or nothing being exported.

**Comment by safaci2000** [comment]
Yeah, that's fair.  My main use case has a combination of User created content and VCS managed data.  So the white list initially was to ensure we don't destroy all the data.  Some of the operation can be very destructive (like clear for example).

I'll add this to the next milestone and happy to take a PR

**Comment by safaci2000** [comment]
@tokheim this is in code review, not sure why GH keeps closing the ticket as soon as i reference them in a branch, but see #52  for the change, should be part of the 0.1.7 release.
