### ISSUE TITLE
Support multiple Grafana

### ISSUE THREAD

**Issue by tuan-phan** [netsage-project/grafana-dashboard-manager#8]
Hi @safaci2000 
Can we support multiple Grafana like wizzy?
E.g: switch to Grafana dev
```
./bin/grafana-dashboard-manager set context grafana dev
```
Thank you,

**Comment by safaci2000** [comment]
It's certainly possible. It wasn't designed with that in mind. I'll have to update a few things and move some configs around but it's certainly doable.

I'll add it to the feature list next time I update the code.

**Comment by tuan-phan** [comment]
Thank you

**Comment by safaci2000** [comment]
@tuan-phan I haven't done a release yet, have a few tickets i want to close out first for the next version, but context should be merged in now.   Keep in mind the config format changed, so have a look at the example closely to update your current config.
